name = "product-preview-extension"
type = "theme"
description = "Visualize curtains in your space using AI"

# Enable network access for API calls
network_access = true

[[extensions]]
type = "theme"
name = "Blinds in My Home"
handle = "blinds-in-my-home"

# Define extension points
[[extensions.targeting]]
module = ["product"]
target = "section"

# Extension settings
[settings]
api_version = "2024-01"

# Assets configuration
[assets]
main = "blocks/product-visualizer.liquid"

# Include additional assets
[[assets.custom]]
path = "assets/visualizer.js"
[[assets.custom]]
path = "assets/visualizer.css"
